name: Generate cmark header files
on:
  push:
    branches: [doesnotexit]
  workflow_dispatch:
jobs:
  generate:
    name: Generate cmake header files for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Patch cmark-gfm
        uses: ./.github/actions/cmark-gfm-patch

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ../third_party/cmark

      - name: Copy (Windows)
        if: runner.os == 'Windows'
        working-directory: ./build
        run: |
          Get-ChildItem -Recurse
          New-Item -ItemType Directory -Force -Path ${{ github.workspace }}/generated/windows
          Copy-Item -Force -Path src/cmark-gfm_export.h -Destination ${{ github.workspace}}/generated/windows
          Copy-Item -Force -Path src/cmark-gfm_version.h -Destination ${{ github.workspace}}/generated/windows
          Copy-Item -Force -Path src/config.h -Destination ${{ github.workspace }}/generated/windows

      - name: Copy (Unix)
        if: runner.os == 'Linux'
        working-directory: ./build
        run: |
          ls -lRa
          mkdir -p ${{ github.workspace }}/generated/unix
          cp src/cmark-gfm_export.h src/cmark-gfm_version.h src/config.h ${{ github.workspace }}/generated/unix

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          add-paths: generated/
          title: Update generated headers for ${{ runner.os }}
          commit-message: Update generated headers for ${{ runner.os }}.
          body: ''
          reviewers: zopieux
          branch: gen-headers-${{ runner.os }}
          branch-suffix: short-commit-hash
          delete-branch: true
